### ISSUE TITLE
can't compile with ghc 8.6.1

### ISSUE THREAD

**Issue by LeventErkok** [elaforge/fast-tags#41]
```
<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules:
        FastTags
[1 of 2] Compiling FastTags         ( src/FastTags.hs, dist/build/fast-tags/fast-tags-tmp/FastTags.o )

src/FastTags.hs:74:21: error:
    • No instance for (Semigroup UnstrippedTokens)
        arising from the 'deriving' clause of a data type declaration
      Possible fix:
        use a standalone 'deriving instance' declaration,
          so you can specify the instance context yourself
    • When deriving the instance for (Monoid UnstrippedTokens)
   |
74 |     deriving (Show, Monoid.Monoid)
   |                     ^^^^^^^^^^^^^
```

**Comment by elaforge** [comment]
Is this 1.5.0?  Do you have an old version?  I say because src/FastTags.hs doesn't even exist any more :)

**Comment by LeventErkok** [comment]
no; this is straight `cabal update; cabal install fast-tags`

**Comment by LeventErkok** [comment]
Full log:

```
Starting     fast-tags-0.0.6
Building     fast-tags-0.0.6
Failed to install fast-tags-0.0.6
Build log ( /Users/LeventErkok/.cabal/logs/ghc-8.6.1/fast-tags-0.0.6-D7qvfN2ucmvLpkbZlMRZkS.log ):
cabal: Entering directory '/var/folders/ty/r22vmk1j7kxc60j8f5l3wgzc0000gn/T/cabal-tmp-11467/fast-tags-0.0.6'
Configuring fast-tags-0.0.6...
Preprocessing executable 'fast-tags' for fast-tags-0.0.6..
Building executable 'fast-tags' for fast-tags-0.0.6..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules:
        FastTags
[1 of 2] Compiling FastTags         ( src/FastTags.hs, dist/build/fast-tags/fast-tags-tmp/FastTags.o )

src/FastTags.hs:74:21: error:
    • No instance for (Semigroup UnstrippedTokens)
        arising from the 'deriving' clause of a data type declaration
      Possible fix:
        use a standalone 'deriving instance' declaration,
          so you can specify the instance context yourself
    • When deriving the instance for (Monoid UnstrippedTokens)
   |
74 |     deriving (Show, Monoid.Monoid)
   |                     ^^^^^^^^^^^^^
cabal: Leaving directory '/var/folders/ty/r22vmk1j7kxc60j8f5l3wgzc0000gn/T/cabal-tmp-11467/fast-tags-0.0.6'
cabal: Error: some packages failed to install:
fast-tags-0.0.6-D7qvfN2ucmvLpkbZlMRZkS failed during the building phase. The
exception was:
ExitFailure 1
```

**Comment by LeventErkok** [comment]
I see what you mean. I've no idea why cabal 2.4.0 is picking 0.0.6 of fast-tags!

**Comment by elaforge** [comment]
Yeah, 0.0.6 is really old.  If you force it with cabal install fast-tags-1.5.0 it should complain about what is preventing that.  Probably I have some upper version bounds which is preventing it, but the only candidate is base <5 and 0.0.6 also has that...

**Comment by LeventErkok** [comment]
I see the problem. It's because of polyparse; which requries an older base. Sigh.

Unfortunately polyparse doesn't install even with `allow-newer` which blocks `fast-tags`.

**Comment by elaforge** [comment]
Ah, polyparse must be a local install.  Build with a sandbox?  And isn't new-build supposed to avoid these problems?

**Comment by LeventErkok** [comment]
beats me. I'll close this as it isn't fast-tags to blame; though you might hear from others for just the same too!
