### ISSUE TITLE
Can't compile with GHC 8.4.1

### ISSUE THREAD

**Issue by LeventErkok** [elaforge/fast-tags#35]
```
src/FastTags/Tag.hs:104:21: error:
    • No instance for (Semigroup UnstrippedTokens)
        arising from the 'deriving' clause of a data type declaration
      Possible fix:
        use a standalone 'deriving instance' declaration,
          so you can specify the instance context yourself
    • When deriving the instance for (Monoid UnstrippedTokens)
    |
104 |     deriving (Show, Monoid)
    |                     ^^^^^^
```

**Comment by elaforge** [comment]
Thanks, just pushed a fix and updated hackage.
